Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -25,21 +25,29 @@ inputs:
     description: 'Path to file containing files list for scanning'
     required: true
 runs:
-  using: 'docker'
-  image: 'docker://plexicus/plexalyzer:latest'
-  entrypoint: '/venvs/plexicus-fastapi/bin/python'
-  env:
-    PLEXALYZER_TOKEN: ${{ inputs.plexalyzer-token }}
-    MESSAGE_URL: 'http://fastapi.covulor-prd.svc.cluster.local:8000/receive_plexalyzer_message'
-  args:
-    - "/app/analyze.py"
-    - "--repository_id"
-    - ${{ inputs.repo-id }}
-    - "--name"
-    - ${{ inputs.repo-name }}
-    - "--branch"
-    - ${{ inputs.branch }}
-    - "--url"
-    - ${{ inputs.url }}
-    - "--files"
-    - ${{ inputs.files-path }}
+  using: 'composite'
+  steps:
+    - name: Output Files List for Debugging
+      id: output-files-list
+      shell: bash
+      run: |
+        echo "Contents of files list:"
+        cat "${{ inputs.files-path }}" || echo "File not found or is empty"
+
+    - name: Run PLEXALYZER Docker Analysis
+      shell: bash
+      env:
+        PLEXALYZER_TOKEN: ${{ inputs.plexalyzer-token }}
+        MESSAGE_URL: 'http://fastapi.covulor-prd.svc.cluster.local:8000/receive_plexalyzer_message'
+      run: |
+        docker run --rm \
+          -e PLEXALYZER_TOKEN="$PLEXALYZER_TOKEN" \
+          -e MESSAGE_URL="$MESSAGE_URL" \
+          -v "${{ inputs.files-path }}:/app/files_to_scan.json" \
+          plexicus/plexalyzer:latest \
+          /venvs/plexicus-fastapi/bin/python /app/analyze.py \
+          --repository_id "${{ inputs.repo-id }}" \
+          --name "${{ inputs.repo-name }}" \
+          --branch "${{ inputs.branch }}" \
+          --url "${{ inputs.url }}" \
+          --files "/app/files_to_scan.json"
